linux: &linux
  os: linux
  dist: bionic
  language: python
  env: CC=gcc-7 CXX=g++-7

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      python: "3.6"
    - <<: *linux
      python: "3.7"
    - <<: *osx
      osx_image: xcode11.3
      env: pyv="3.6.10"
    - <<: *osx
      osx_image: xcode11.3
      env: pyv="3.7.6"
    - <<: *linux  #test conda
      language: generic
      env: test_conda="1" pyv="3.6"
    - <<: *linux  #test conda
      language: generic
      env: test_conda="1" pyv="3.7"
    - <<: *osx    #test conda
      osx_image: xcode11.3
      env: test_conda="1" pyv="3.6"
    - <<: *osx #test conda
      osx_image: xcode11.3
      env: test_conda="1" pyv="3.7"



before_install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - git clone https://github.com/Chrismarsh/Windmapper.git
  - (cd Windmapper && git checkout $TRAVIS_BRANCH)
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$test_conda" != "1" ]; then eval "$(pyenv init -)"; pyenv activate Windmapper         ; fi
  - if [ "$test_conda" = "1" ]; then source $HOME/conda/bin/activate; conda activate Windmapper ; fi
  - pip install --upgrade pip
  - pip install ./Windmapper/
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$test_conda" != "1" ]; then eval "$(pyenv init -)";pyenv activate Windmapper         ; fi
  - if [ "$test_conda" = "1" ]; then source $HOME/conda/bin/activate; conda activate Windmapper ; fi
  - cd Windmapper/examples
  - echo "running tests"
  - bash ./runall.sh &> /dev/null
deploy:
  provider: script
  script: cd .. && pwd && ls -la && bash ./.travis/deploy.sh
  on:
    tags: true